

all:	stub	sample1	sample2	sample3

stub:	stub.c
	gcc -lconfig -o sample1 sample1.c

sample1:	sample1.c
	gcc -lconfig -o sample1 sample1.c

sample2:	sample2.c
	gcc -lconfig -o sample2 sample2.c

sample3:	sample3.c
	gcc -lconfig -o sample3 sample3.c

