
all:	stubcpp	sample1	sample2	sample3

stubcpp:	stubcpp.cpp
	g++ -lconfig++ -o stubcpp stubcpp.cpp

sample1:	sample1.cpp
	g++ -lconfig++ -o sample1 sample1.cpp

sample2:	sample2.cpp
	g++ -lconfig++ -o sample2 sample2.cpp

sample3:	sample3.cpp
	g++ -lconfig++ -o sample3 sample3.cpp

